app/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from app.config import Keys
from app.main.routes import main

bcrypt = Bcrypt()

def create_app(config_class=Keys):
    project = Flask(__name__)
    project.config.from_object(Keys)
    bcrypt.init_app(project)
    project.register_blueprint(main)

    return project

app/main/routes.py
from flask import render_template, request, Blueprint, jsonify
from app.prediction_functions import route_accPrediction
import datetime as dt
import json
import traceback

main = Blueprint('main', __name__)

# home page
@main.route("/")
@main.route("/home")
def home():
    return render_template('index.html')


@main.route("/route_prediction")
def route_prediction():
    return render_template('route_prediction.html')

#API to get user inputs
@main.route('/prediction', methods=['POST'])
def prediction():
    try:
        req_data = request.get_json()
        origin = req_data['origin']
        destination = req_data['destination']
        date_time = req_data['datetime']
        print(date_time)
        #process time
        tm = dt.datetime.strptime(date_time,'%Y/%m/%d %H:%M').strftime('%Y-%m-%dT%H:%M')

        out = route_accPrediction(origin, destination, tm)

        return json.dumps(out)

    except:

        return jsonify({'trace': traceback.format_exc()})

app/templates/index.html
<!DOCTYPE HTML>
<!--
	Ethereal by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>SafeRoute AI</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"/>
		<noscript><link rel="stylesheet" href="{{ url_for('static', filename='css/noscript.css') }}"/></noscript>
	</head>
	<body class="is-preload">

		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Wrapper -->
					<div id="wrapper">

						<!-- Panel (Banner) -->
							<section class="panel banner right">
                                <div class="content color0 span-3-75">
                                    <h1 class="major">
                                        SafeRoute AI
                                    </h1>
                                    <h2>MSc Group Project</h2>
                                    <h5>Muhammad Afeef</h5><h5>Sana Hidayat Ullah</h5><h5>Abdul Rafay</h5><h5>Kurushanth K</h5><h5>Filbert Kiptanui</h5>
                                    <ul class="actions">
                                        <li><a href="#first" class="button primary color1 circle icon solid fa-angle-right">Next</a></li>
                                    </ul>
                                </div>
								<div class="image filtered span-1-75" data-position="25% 25%">
									<img src="static/images/pic01.jpg" alt="" />
								</div>
							</section>

							<section class="panel spotlight medium right" id="first">
								<div class="content span-7">
                                    <h2 class="major">
                                        <a href="{{ url_for('main.route_prediction') }}" 
                                           style="border: 1px solid; border-color: gray" 
                                           onclick="window.open('{{ url_for('main.route_prediction') }}', 'RoutePrediction', 'width=1366,height=760,toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes'); return false;">
                                            Click here to travel safely
                                        </a>
                                    </h2>
									<p style="text-align:left; font-size:150%;">Tell the predictor a starting and ending point along with desired time and it will predict the number of accidents on your route.</p>
								</div>
								<div class="image filtered tinted" data-position="top left">
									
									<img src="static/images/pic_cars.jpg" alt="" />
								</div>
							</section>

						<!-- Copyright -->
							<div class="copyright">&copy;Final Year Project (NUML)</div>

					</div>

			</div>

		<!-- Scripts -->
			<script src="static/js/jquery.min.js"></script>
			<script src="static/js/browser.min.js"></script>
			<script src="static/js/breakpoints.min.js"></script>
			<script src="static/js/main.js"></script>

	</body>
</html>

app/templates/route_prediction.html
<!DOCTYPE html>
<html>
<head>
    <title>SafeRoute AI Predictor</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.datetimepicker.min.css') }}"/>
    <style>
        #loading {
              width: 100%;
              height: 100%;
              top: 0;
              left: 0;
              position: fixed;
              display: block;
              opacity: 0.7;
              background-color: #fff;
              z-index: 99;
              text-align: center;
              }
        #loading-image {
              position: absolute;
              top: 100px;
              left: 240px;
              z-index: 100;
              }
        /* Always set the map height explicitly to define the size of the div
         * element that contains the map. */
        #map {
            height: 100%;
        }
        /* Optional: Makes the sample page fill the window. */
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
        .controls {
            margin-top: 10px;
            border: 1px solid transparent;
            border-radius: 2px 0 0 2px;
            box-sizing: border-box;
            -moz-box-sizing: border-box;
            height: 32px;
            outline: none;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        }
        #datetime-input,
        #origin-input,
        #destination-input {
            background-color: #fff;
            font-family: Roboto;
            font-size: 15px;
            font-weight: 300;
            margin-left: 12px;
            padding: 0 11px 0 13px;
            text-overflow: ellipsis;
            width: 200px;
        }
        #origin-input:focus,
        #destination-input:focus {
            border-color: #4d90fe;
        }
        #mode-selector {
            color: #fff;
            background-color: #4d90fe;
            margin-left: 12px;
            padding: 5px 11px 0px 11px;
        }
        #mode-selector label {
            font-family: Roboto;
            font-size: 13px;
            font-weight: 300;
        }
        .top-controls {
            position: absolute;
            top: 10px;
            left: 50%;
            transform: translateX(-50%);
            display: flex;
            gap: 10px;
        }

        .top-right-controls {
            position: absolute;
            top: 10px;
            right: 10px;
        }
    </style>
</head>
<body>
  <!-- add loading screen-->
  <div id="loading">
    <img id="loading-image" src="https://cdn-images-1.medium.com/max/800/1*9EBHIOzhE1XfMYoKz1JcsQ.gif" alt="Loading..." />

  </div>


<div class="top-controls">
    <input id="origin-input" class="controls" type="text" placeholder="Enter an origin location">
    <input id="destination-input" class="controls" type="text" placeholder="Enter a destination location">
    <input id="datetime-input" class="controls" type="text" autocomplete="off" name="datetime" placeholder="Enter a date and time">
</div>
<div class="top-right-controls">
    <input id="refresh" type="reset" value="Refresh Input" onClick="document.location.reload(true)">
</div>

<div id="map"></div>

<script>
    // This example requires the Places library. Include the libraries=places
    // parameter when you first load the API. For example:
    // <script
    // src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">
    var map;
    var markers = [];
    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            mapTypeControl: false,
            center: {lat: 51.5058, lng: -0.1},
            zoom: 13
        });
        new AutocompleteDirectionsHandler(map);
    }
    /**
     * @constructor
     */
    function AutocompleteDirectionsHandler(map) {
        this.map = map;
        this.originPlaceId = null;
        this.destinationPlaceId = null;
        this.directionsDisplay = new google.maps.DirectionsRenderer({
            map: map,
            suppressMarkers: true,
            polylineOptions: {
                strokeColor: '#4285F4',
                strokeWeight: 4
            }
        });
        
        //datetime picker
        $(function () {
            var date = new Date();
            var currentMonth = date.getMonth();
            var currentYear = date.getFullYear();
            var currentDate = date.getDate() + 2;
            $("#datetime-input").datetimepicker({maxDate: new Date(currentYear, currentMonth, currentDate)});
        });

        var originInput = document.getElementById('origin-input');
        var destinationInput = document.getElementById('destination-input');
        var datetimeInput = document.getElementById('datetime-input');

        // Store autocomplete instances as class properties
        this.originAutocomplete = new google.maps.places.Autocomplete(originInput);
        this.destinationAutocomplete = new google.maps.places.Autocomplete(destinationInput);

        // Specify just the place data fields that you need.
        this.originAutocomplete.setFields(['place_id', 'geometry']);
        this.destinationAutocomplete.setFields(['place_id', 'geometry']);

        this.setupPlaceChangedListener(this.originAutocomplete, 'ORIG');
        this.setupPlaceChangedListener(this.destinationAutocomplete, 'DEST');

        this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(datetimeInput);
        this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(originInput);
        this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(destinationInput);
        this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(refresh);
    }

    AutocompleteDirectionsHandler.prototype.setupPlaceChangedListener = function(
        autocomplete, mode) {
        var me = this;
        autocomplete.bindTo('bounds', this.map);
        autocomplete.addListener('place_changed', function() {
            var place = autocomplete.getPlace();
            if (!place.place_id) {
                window.alert('Please select an option from the dropdown list.');
                return;
            }
            if (mode === 'ORIG') {
                me.originPlaceId = place.place_id;
            } else {
                me.destinationPlaceId = place.place_id;
            }
            me.route();
        });
    };
    AutocompleteDirectionsHandler.prototype.route = function() {
        if (!this.originPlaceId || !this.destinationPlaceId) {
            return;
        }
        var me = this;

        // Get the place details for origin and destination
        var originPlace = this.originAutocomplete.getPlace();
        var destinationPlace = this.destinationAutocomplete.getPlace();

        if (!originPlace.geometry || !destinationPlace.geometry) {
            window.alert('Please select valid locations from the dropdown list.');
            return;
        }

        // Get and format the departure time
        var datetimeInput = document.getElementById("datetime-input").value;
        var departureTime = new Date(datetimeInput).toISOString();

        // Prepare the Routes API request
        var request = {
            origin: {
                location: {
                    latLng: {
                        latitude: originPlace.geometry.location.lat(),
                        longitude: originPlace.geometry.location.lng()
                    }
                }
            },
            destination: {
                location: {
                    latLng: {
                        latitude: destinationPlace.geometry.location.lat(),
                        longitude: destinationPlace.geometry.location.lng()
                    }
                }
            },
            travelMode: 'DRIVE',
            polylineQuality: 'OVERVIEW',
            routingPreference: 'TRAFFIC_AWARE',
            departureTime: departureTime,
            computeAlternativeRoutes: false
        };

        console.log("Travel Mode:", request.travelMode);
        // Make the Routes API request
        fetch('https://routes.googleapis.com/directions/v2:computeRoutes', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-Goog-Api-Key': 'AIzaSyC4iPRBjrfCPGK-LBbfAD-1U244dxFyvYI',
                'X-Goog-FieldMask': 'routes.duration,routes.distanceMeters,routes.polyline,routes.legs'
            },
            body: JSON.stringify(request)
        })
        .then(response => {
            if (!response.ok) {
                return response.json().then(err => {
                    throw new Error(err.error?.message || `HTTP error! status: ${response.status}`);
                });
            }
            return response.json();
        })
        .then(result => {
            console.log(result);
            if (result.routes && result.routes.length > 0) {
                const route = result.routes[0];
                const polyline = renderRoute(map, route.polyline.encodedPolyline);
                map.fitBounds({
                    north: Math.max(...route.legs.map(leg => leg.startLocation.latLng.latitude)),
                    south: Math.min(...route.legs.map(leg => leg.endLocation.latLng.latitude)),
                    east: Math.max(...route.legs.map(leg => leg.startLocation.latLng.longitude)),
                    west: Math.min(...route.legs.map(leg => leg.endLocation.latLng.longitude))
                });
            } else {
                window.alert('No route found between the selected locations.');
            }
        })
        .catch(error => {
            console.error('Routes API Error:', error);
            window.alert(error.message || 'Failed to get route. Please try again.');
        });

        // Send prediction request
        var xhr = new XMLHttpRequest();
        var url = "{{ url_for('main.prediction') }}";
        xhr.open("POST", url, true);
        xhr.setRequestHeader("Content-Type", "application/json");
        xhr.onreadystatechange = function () {
            if (xhr.readyState === 4 && xhr.status === 200) {
                var json = JSON.parse(xhr.responseText);
                console.log(json);
                if(json == null ) {
                    window.alert('No accident predicted with current input. Click "Refresh Input" for next prediction');
                } else {
                    display_results(json);
                }
            }
        };
        var data = JSON.stringify({
            "origin": document.getElementById("origin-input").value,
            "destination": document.getElementById("destination-input").value,
            "datetime": document.getElementById("datetime-input").value
        });
        xhr.send(data);
    };
	function display_results(accident_json) {

        var icon = {
          url:'https://cdn1.iconfinder.com/data/icons/ui-navigation-1/152/marker-512.png',
          scaledSize: new google.maps.Size(32, 32), // scaled size
        };

        var count = Object.keys(accident_json.accidents).length;
        console.log(count);
        window.alert(count + ' accidents found. Click "Refresh Input" for next prediction');
        setMapOnAll(null);
        markers = [];
        for(var i = 0; i < count; i++) {
            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(accident_json.accidents[i].lat, accident_json.accidents[i].lng),
                map: map,
                title: 'Probability: ' + (accident_json.accidents[i].probability * 100).toFixed(2) + "%",
                icon: icon
            });
            markers.push(marker);
        }
        // marker.setMap(map);
        setMapOnAll(map);
    }
    // Sets the map on all markers in the array.
    function setMapOnAll(map) {
        for (var i = 0; i < markers.length; i++) {
            markers[i].setMap(map);
        }
    }
    //var markerArray = [];
    function showSteps(directionResult) {
        // For each step, place a marker, and add the text to the marker's
        // info window. Also attach the marker to an array so we
        // can keep track of it and remove it when calculating new
        // routes.
        var myRoute = directionResult.routes[0].legs[0];
        for (var i = 0; i < myRoute.steps.length; i++) {
            var marker = new google.maps.Marker({
                position: myRoute.steps[i].start_point,
                map: map
            });
            // console.log("Step:" + i + "," + myRoute.steps[i].start_point);
            attachInstructionText(marker, myRoute.steps[i].instructions);
            //markerArray[i] = marker;
        }
    }
    function attachInstructionText(marker, text) {
        google.maps.event.addListener(marker, 'click', function() {
            stepDisplay.setContent(text);
            stepDisplay.open(map, marker);
        });
    }
    function renderRoute(map, encodedPolyline) {
        const polyline = new google.maps.Polyline({
            path: google.maps.geometry.encoding.decodePath(encodedPolyline),
            strokeColor: "#4285F4",
            strokeWeight: 4,
            map: map
        });
        return polyline;
    }
// https://stackoverflow.com/questions/1006654/fastest-way-to-find-distance-between-two-lat-long-points
</script>
<script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC4iPRBjrfCPGK-LBbfAD-1U244dxFyvYI&libraries=places,marker&callback=initMap">

</script>
<script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.datetimepicker.full.js') }}"></script>
<script language="javascript" type="text/javascript">
     $(window).load(function() {
     $('#loading').hide();
  });
</script>
</body>
</html>